<a href="https://colab.research.google.com/github/jtinklerdav/jtinklerdav.github.io/blob/main/regression_Islam_consumption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

Now I am creating a dataframe that is reading the html code of the website below. This code reads the html and selects the tables from the site. By using inspect element I was able to determine that the table could be scraped in Colab. The Table shows the Muslim population in every country in a study conducted by the Pew Forum Research Centre

In [ ]:
df = pd.read_html('https://web.archive.org/web/20110202124356/http://features.pewforum.org/muslim-population/')
df

[      0     1     2
 0   Jan   FEB   Apr
 1   NaN    02   NaN
 2  2010  2011  2012,
                Country Estimated 1990 Muslim Population  \
 0          Afghanistan                         12551000
 1              Albania                          2302000
 2              Algeria                         24860000
 3       American Samoa                          < 1,000
 4              Andorra                          < 1,000
 ..                 ...                              ...
 227  Wallis and Futuna                          < 1,000
 228     Western Sahara                           221000
 229              Yemen                         12191000
 230             Zambia                            33000
 231           Zimbabwe                            94000

     Percentage of 1990 Population that is Muslim  \
 0                                           99.8
 1                                           70.0
 2                                           98.3
 3                                          < 0.1
 4                                            0.5
 ..                                           ...
 227                                        < 0.1
 228                                         99.9
 229                                         99.0
 230                                          0.4
 231                                          0.9

     Estimated 2010 Muslim Population  \
 0                           29047000
 1                            2601000
 2                           34780000
 3                            < 1,000
 4                               1000
 ..                               ...
 227                          < 1,000
 228                           528000
 229                         24023000
 230                            59000
 231                           109000

     Percentage of 2010 Population that is Muslim  \
 0                                           99.8
 1                                           82.1
 2                                           98.2
 3                                          < 0.1
 4                                            1.1
 ..                                           ...
 227                                        < 0.1
 228                                         99.6
 229                                         99.0
 230                                          0.4
 231                                          0.9

     Projected 2030 Muslim Population*  \
 0                            50527000
 1                             2841000
 2                            43915000
 3                             < 1,000
 4                                1000
 ..                                ...
 227                           < 1,000
 228                            816000
 229                          38973000
 230                             94000
 231                            155000

     Projected Percentage of 2030 Population that is Muslim*
 0                                                 99.8
 1                                                 83.2
 2                                                 98.2
 3                                                < 0.1
 4                                                  1.1
 ..                                                 ...
 227                                              < 0.1
 228                                               99.6
 229                                               99.0
 230                                                0.4
 231                                                0.9

 [232 rows x 7 columns]]

Having created a dataframe with the tables from the site, I am checking how many tables are in the array scraped and which one has the data desired. From using the len() function I know that there are 2 tables in the array and from looking at each one I know that the second table in the array contains the desired information

In [ ]:
len(df)

2

In [ ]:
df2 = df[1]
df2

,Country,Estimated 1990 Muslim Population,Percentage of 1990 Population that is Muslim,Estimated 2010 Muslim Population,Percentage of 2010 Population that is Muslim,Projected 2030 Muslim Population*,Projected Percentage of 2030 Population that is Muslim*
0,Afghanistan,12551000,99.8,29047000,99.8,50527000,99.8
1,Albania,2302000,70.0,2601000,82.1,2841000,83.2
2,Algeria,24860000,98.3,34780000,98.2,43915000,98.2
3,American Samoa,"< 1,000",< 0.1,"< 1,000",< 0.1,"< 1,000",< 0.1
4,Andorra,"< 1,000",0.5,1000,1.1,1000,1.1
...,...,...,...,...,...,...,...
227,Wallis and Futuna,"< 1,000",< 0.1,"< 1,000",< 0.1,"< 1,000",< 0.1
228,Western Sahara,221000,99.9,528000,99.6,816000,99.6
229,Yemen,12191000,99.0,24023000,99.0,38973000,99.0
230,Zambia,33000,0.4,59000,0.4,94000,0.4
231,Zimbabwe,94000,0.9,109000,0.9,155000,0.9

Now that I have scraped the table succeffully into Colab I am dropping the columns that are unnecessary for the regression I am going to undertake. These are the Projections for 2030 and the 1990 values. I am also renaming the columns to simplify my code

In [ ]:
df3 = df2.drop(['Estimated 1990 Muslim Population','Percentage of 1990 Population that is Muslim','Projected 2030 Muslim Population*','Projected Percentage of 2030 Population that is Muslim*'],axis=1)
df3

,Country,Estimated 2010 Muslim Population,Percentage of 2010 Population that is Muslim
0,Afghanistan,29047000,99.8
1,Albania,2601000,82.1
2,Algeria,34780000,98.2
3,American Samoa,"< 1,000",< 0.1
4,Andorra,1000,1.1
...,...,...,...
227,Wallis and Futuna,"< 1,000",< 0.1
228,Western Sahara,528000,99.6
229,Yemen,24023000,99.0
230,Zambia,59000,0.4
231,Zimbabwe,109000,0.9

In [ ]:
df4 = df3.rename(columns={'Estimated 2010 Muslim Population':'Muslim Population','Percentage of 2010 Population that is Muslim':'Percentage'})

Having renamed the columns I needed to rename a number of the Country names so that they would maytch up with the other dataset when merging the two. Therefore I manually sorted through the data and renamed the required countries so as to not affect the dataset

In [ ]:
df4['Country'] = df4['Country'].replace({'Swaziland': 'Eswatini','Congo':'The Democratic Republic of Congo','Cape Verde':'Cabo Verde','Guinea Bissau':'Guinea-Bissau',"Ivory Coast":"Cote d'Ivoire", 'Laos':"Lao People's Democratic Republic",'Burma (Myanmar)': 'Myanmar', 'South Korea':'Korea, Republic of', 'Faeroe Islands':'Faroe Islands','Bosnia-Herzegovina':'Bosnia and Herzegovina','Republic of Macedonia': 'North Macedonia', 'Slovakia':'Slovak Republic','Czech Republic':'Czechia','Russia':"Russian Federation",'St. Kitts and Nevis': 'Saint Kitts and Nevis','St. Vincent and the Grenadines':'Saint Vincent and the Grenadines','St. Lucia':'Saint Lucia','Macau':'Macao'})
df5=df4

Now that I have my cleaned data for the first source (Muslim %), I am importing a csv of Wine Consumption per capita (calculated in Excel).

In [ ]:
df2_1 = pd.read_csv('Islam_regression.csv')
df2_1

,Continent,Country Name,2010 Consumption (litres),Consumption pc,GDP pc,Population,Population (thousands)
0,Asia,Afghanistan,200000,0.005138,516.75,38928341,38928.34
1,Europe,Albania,20600000,7.259019,5332.16,2837849,2837.85
2,Africa,Algeria,28000000,0.638525,3306.86,43851043,43851.04
3,Africa,Angola,86800000,2.641006,1631.43,32866268,32866.27
4,North America,Antigua and Barbuda,600000,6.126950,13992.74,97928,97.93
...,...,...,...,...,...,...,...
162,Asia,Uzbekistan,13000000,0.379761,1749.66,34232050,34232.05
163,Oceania,Vanuatu,500000,1.627869,2919.84,307150,307.15
164,Asia,Vietnam,10200000,0.104789,3526.27,97338583,97338.58
165,Africa,Zambia,500000,0.027198,985.13,18383956,18383.96
166,Africa,Zimbabwe,3800000,0.255670,1214.51,14862927,14862.93

In [ ]:
df2_2 = df2_1.drop(['2010 Consumption (litres)'],axis=1)
df2_2

,Continent,Country Name,Consumption pc,GDP pc,Population,Population (thousands)
0,Asia,Afghanistan,0.005138,516.75,38928341,38928.34
1,Europe,Albania,7.259019,5332.16,2837849,2837.85
2,Africa,Algeria,0.638525,3306.86,43851043,43851.04
3,Africa,Angola,2.641006,1631.43,32866268,32866.27
4,North America,Antigua and Barbuda,6.126950,13992.74,97928,97.93
...,...,...,...,...,...,...
162,Asia,Uzbekistan,0.379761,1749.66,34232050,34232.05
163,Oceania,Vanuatu,1.627869,2919.84,307150,307.15
164,Asia,Vietnam,0.104789,3526.27,97338583,97338.58
165,Africa,Zambia,0.027198,985.13,18383956,18383.96
166,Africa,Zimbabwe,0.255670,1214.51,14862927,14862.93

In [ ]:
df2_3 = df2_2.rename(columns={'Country Name': 'Country'})

I had to rename the 'Country Name' column since the two columns need to match up when merging datasets. Below I have merged the two datasets. In the code I have merged based on Country name (hence why editing the names was so vital earlier) and i have merged it on the 'right' dataset. This is the df2_3 dataset since it has fewer values so less sorting is required after merging

In [ ]:
merge_df = df5.merge(df2_3, on=['Country'], how='right')
merge_df

,Country,Muslim Population,Percentage,Continent,Consumption pc,GDP pc,Population,Population (thousands)
0,Afghanistan,29047000,99.8,Asia,0.005138,516.75,38928341,38928.34
1,Albania,2601000,82.1,Europe,7.259019,5332.16,2837849,2837.85
2,Algeria,34780000,98.2,Africa,0.638525,3306.86,43851043,43851.04
3,Angola,195000,1.0,Africa,2.641006,1631.43,32866268,32866.27
4,Antigua and Barbuda,"< 1,000",0.6,North America,6.126950,13992.74,97928,97.93
...,...,...,...,...,...,...,...,...
162,Uzbekistan,26833000,96.5,Asia,0.379761,1749.66,34232050,34232.05
163,Vanuatu,"< 1,000",< 0.1,Oceania,1.627869,2919.84,307150,307.15
164,Vietnam,160000,0.2,Asia,0.104789,3526.27,97338583,97338.58
165,Zambia,59000,0.4,Africa,0.027198,985.13,18383956,18383.96
166,Zimbabwe,109000,0.9,Africa,0.255670,1214.51,14862927,14862.93

Having done this I recognised that some of the data in the table will affect my regression. Since I am regressing percentage I need to remove all the observations that are labelled "<0.1", they are not numeric values and are nearing 0 so I have removed them at the extremety of observations

I used the drop() function to remove all the rows with that as their value for Percentage

In [ ]:
merge_df2 = merge_df.drop(merge_df[merge_df['Percentage']=='< 0.1'].index)
merge_df2

,Country,Muslim Population,Percentage,Continent,Consumption pc,GDP pc,Population,Population (thousands)
0,Afghanistan,29047000,99.8,Asia,0.005138,516.75,38928341,38928.34
1,Albania,2601000,82.1,Europe,7.259019,5332.16,2837849,2837.85
2,Algeria,34780000,98.2,Africa,0.638525,3306.86,43851043,43851.04
3,Angola,195000,1.0,Africa,2.641006,1631.43,32866268,32866.27
4,Antigua and Barbuda,"< 1,000",0.6,North America,6.126950,13992.74,97928,97.93
...,...,...,...,...,...,...,...,...
160,United States,2595000,0.8,North America,8.250350,63027.68,331501080,331501.08
162,Uzbekistan,26833000,96.5,Asia,0.379761,1749.66,34232050,34232.05
164,Vietnam,160000,0.2,Asia,0.104789,3526.27,97338583,97338.58
165,Zambia,59000,0.4,Africa,0.027198,985.13,18383956,18383.96
166,Zimbabwe,109000,0.9,Africa,0.255670,1214.51,14862927,14862.93

In [ ]:
exported_values = list(merge_df2.T.to_dict().values())

In [ ]:
import json

In [ ]:
open('regression.json','w').write(json.dumps(exported_values))

29481

In [ ]:
json.dumps(exported_values)

'[{"Country": "Afghanistan", "Muslim Population": "29047000", "Percentage": "99.8", "Continent": "Asia", "Consumption pc": 0.005137645, "GDP pc": 516.75, "Population": 38928341, "Population (thousands)": 38928.34}, {"Country": "Albania", "Muslim Population": "2601000", "Percentage": "82.1", "Continent": "Europe", "Consumption pc": 7.259019067, "GDP pc": 5332.16, "Population": 2837849, "Population (thousands)": 2837.85}, {"Country": "Algeria", "Muslim Population": "34780000", "Percentage": "98.2", "Continent": "Africa", "Consumption pc": 0.638525291, "GDP pc": 3306.86, "Population": 43851043, "Population (thousands)": 43851.04}, {"Country": "Angola", "Muslim Population": "195000", "Percentage": "1.0", "Continent": "Africa", "Consumption pc": 2.641005666, "GDP pc": 1631.43, "Population": 32866268, "Population (thousands)": 32866.27}, {"Country": "Antigua and Barbuda", "Muslim Population": "< 1,000", "Percentage": "0.6", "Continent": "North America", "Consumption pc": 6.126950413, "GDP pc": 13992.74, "Population": 97928, "Population (thousands)": 97.93}, {"Country": "Argentina", "Muslim Population": "1000000", "Percentage": "2.5", "Continent": "South America", "Consumption pc": 21.49337977, "GDP pc": 8585.69, "Population": 45376763, "Population (thousands)": 45376.76}, {"Country": "Australia", "Muslim Population": "399000", "Percentage": "1.9", "Continent": "Oceania", "Consumption pc": 20.97436655, "GDP pc": 51680.32, "Population": 25693267, "Population (thousands)": 25693.27}, {"Country": "Austria", "Muslim Population": "475000", "Percentage": "5.7", "Continent": "Europe", "Consumption pc": 26.91529219, "GDP pc": 48588.66, "Population": 8916864, "Population (thousands)": 8916.86}, {"Country": "Azerbaijan", "Muslim Population": "8795000", "Percentage": "98.4", "Continent": "Asia", "Consumption pc": 0.792619052, "GDP pc": 4229.91, "Population": 10093121, "Population (thousands)": 10093.12}, {"Country": "Bahamas", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "North America", "Consumption pc": 7.6287737, "GDP pc": 24665.1, "Population": 393248, "Population (thousands)": 393.25}, {"Country": "Bahrain", "Muslim Population": "655000", "Percentage": "81.2", "Continent": "Asia", "Consumption pc": 1.469220132, "GDP pc": 20406.5, "Population": 1701583, "Population (thousands)": 1701.58}, {"Country": "Bangladesh", "Muslim Population": "148607000", "Percentage": "90.4", "Continent": "Asia", "Consumption pc": 0.000607204, "GDP pc": 2270.35, "Population": 164689383, "Population (thousands)": 164689.38}, {"Country": "Barbados", "Muslim Population": "2000", "Percentage": "0.9", "Continent": "North America", "Consumption pc": 7.655608951, "GDP pc": 16318.75, "Population": 287371, "Population (thousands)": 287.37}, {"Country": "Belarus", "Muslim Population": "19000", "Percentage": "0.2", "Continent": "Europe", "Consumption pc": 7.29214819, "GDP pc": 6555.43, "Population": 9379952, "Population (thousands)": 9379.95}, {"Country": "Belgium", "Muslim Population": "638000", "Percentage": "6.0", "Continent": "Europe", "Consumption pc": 23.90802479, "GDP pc": 45189.37, "Population": 11544241, "Population (thousands)": 11544.24}, {"Country": "Belize", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "North America", "Consumption pc": 1.005983084, "GDP pc": 3987.8, "Population": 397621, "Population (thousands)": 397.62}, {"Country": "Benin", "Muslim Population": "2259000", "Percentage": "24.5", "Continent": "Africa", "Consumption pc": 0.461924321, "GDP pc": 1291.04, "Population": 12123198, "Population (thousands)": 12123.2}, {"Country": "Bermuda", "Muslim Population": "< 1,000", "Percentage": "0.8", "Continent": "North America", "Consumption pc": 32.86745027, "GDP pc": 107706.04, "Population": 63893, "Population (thousands)": 63.89}, {"Country": "Bosnia and Herzegovina", "Muslim Population": "1564000", "Percentage": "41.6", "Continent": "Europe", "Consumption pc": 3.535706829, "GDP pc": 6082.37, "Population": 3280815, "Population (thousands)": 3280.82}, {"Country": "Botswana", "Muslim Population": "8000", "Percentage": "0.4", "Continent": "Africa", "Consumption pc": 2.423855844, "GDP pc": 6348.83, "Population": 2351625, "Population (thousands)": 2351.63}, {"Country": "Brazil", "Muslim Population": "204000", "Percentage": "0.1", "Continent": "South America", "Consumption pc": 1.734103429, "GDP pc": 6814.88, "Population": 212559409, "Population (thousands)": 212559.41}, {"Country": "Bulgaria", "Muslim Population": "1002000", "Percentage": "13.4", "Continent": "Europe", "Consumption pc": 8.58088712, "GDP pc": 10079.2, "Population": 6934015, "Population (thousands)": 6934.02}, {"Country": "Burkina Faso", "Muslim Population": "9600000", "Percentage": "58.9", "Continent": "Africa", "Consumption pc": 0.196141486, "GDP pc": 857.93, "Population": 20903278, "Population (thousands)": 20903.28}, {"Country": "Burundi", "Muslim Population": "184000", "Percentage": "2.2", "Continent": "Africa", "Consumption pc": 0.016819753, "GDP pc": 233.84, "Population": 11890781, "Population (thousands)": 11890.78}, {"Country": "Cabo Verde", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "Africa", "Consumption pc": 8.992999849, "GDP pc": 3064.27, "Population": 555988, "Population (thousands)": 555.99}, {"Country": "Cambodia", "Muslim Population": "240000", "Percentage": "1.6", "Continent": "Asia", "Consumption pc": 0.047849835, "GDP pc": 1547.51, "Population": 16718971, "Population (thousands)": 16718.97}, {"Country": "Cameroon", "Muslim Population": "3598000", "Percentage": "18.0", "Continent": "Africa", "Consumption pc": 0.342802932, "GDP pc": 1537.13, "Population": 26545864, "Population (thousands)": 26545.86}, {"Country": "Canada", "Muslim Population": "940000", "Percentage": "2.8", "Continent": "North America", "Consumption pc": 11.99877888, "GDP pc": 43258.26, "Population": 38037204, "Population (thousands)": 38037.2}, {"Country": "Central African Republic", "Muslim Population": "403000", "Percentage": "8.9", "Continent": "Africa", "Consumption pc": 0.124229673, "GDP pc": 481.75, "Population": 4829764, "Population (thousands)": 4829.76}, {"Country": "Chad", "Muslim Population": "6404000", "Percentage": "55.7", "Continent": "Africa", "Consumption pc": 0.115671272, "GDP pc": 652.35, "Population": 16425859, "Population (thousands)": 16425.86}, {"Country": "China", "Muslim Population": "23308000", "Percentage": "1.8", "Continent": "Asia", "Consumption pc": 1.075756502, "GDP pc": 10408.67, "Population": 1411100000, "Population (thousands)": 1411100.0}, {"Country": "Comoros", "Muslim Population": "679000", "Percentage": "98.3", "Continent": "Africa", "Consumption pc": 0.114996061, "GDP pc": 1407.41, "Population": 869595, "Population (thousands)": 869.6}, {"Country": "Cote d\'Ivoire", "Muslim Population": "7960000", "Percentage": "36.9", "Continent": "Africa", "Consumption pc": 1.133508541, "GDP pc": 2325.72, "Population": 26378275, "Population (thousands)": 26378.28}, {"Country": "Croatia", "Muslim Population": "56000", "Percentage": "1.3", "Continent": "Europe", "Consumption pc": 37.79943079, "GDP pc": 14132.49, "Population": 4047680, "Population (thousands)": 4047.68}, {"Country": "Cuba", "Muslim Population": "10000", "Percentage": "0.1", "Continent": "North America", "Consumption pc": 1.412601963, "GDP pc": 9477.85, "Population": 11326616, "Population (thousands)": 11326.62}, {"Country": "Cyprus", "Muslim Population": "200000", "Percentage": "22.7", "Continent": "Europe", "Consumption pc": 13.00356728, "GDP pc": 27681.57, "Population": 1207361, "Population (thousands)": 1207.36}, {"Country": "Denmark", "Muslim Population": "226000", "Percentage": "4.1", "Continent": "Europe", "Consumption pc": 27.93495357, "GDP pc": 61063.32, "Population": 5831404, "Population (thousands)": 5831.4}, {"Country": "Djibouti", "Muslim Population": "853000", "Percentage": "97.0", "Continent": "Africa", "Consumption pc": 0.30364311, "GDP pc": 3219.7, "Population": 988002, "Population (thousands)": 988.0}, {"Country": "Dominica", "Muslim Population": "< 1,000", "Percentage": "0.2", "Continent": "North America", "Consumption pc": 2.778125043, "GDP pc": 7003.86, "Population": 71991, "Population (thousands)": 71.99}, {"Country": "Egypt", "Muslim Population": "80024000", "Percentage": "94.7", "Continent": "Africa", "Consumption pc": 0.078175079, "GDP pc": 3569.21, "Population": 102334403, "Population (thousands)": 102334.4}, {"Country": "Estonia", "Muslim Population": "2000", "Percentage": "0.1", "Continent": "Europe", "Consumption pc": 11.11914953, "GDP pc": 23054.36, "Population": 1402985, "Population (thousands)": 1402.99}, {"Country": "Eswatini", "Muslim Population": "2000", "Percentage": "0.2", "Continent": "Africa", "Consumption pc": 0.225652304, "GDP pc": 3434.72, "Population": 1329479, "Population (thousands)": 1329.48}, {"Country": "Ethiopia", "Muslim Population": "28721000", "Percentage": "33.8", "Continent": "Africa", "Consumption pc": 1.637699498, "GDP pc": 936.45, "Population": 1160164, "Population (thousands)": 1160.16}, {"Country": "Fiji", "Muslim Population": "54000", "Percentage": "6.3", "Continent": "Oceania", "Consumption pc": 18.41809066, "GDP pc": 5102.84, "Population": 48865, "Population (thousands)": 48.87}, {"Country": "Finland", "Muslim Population": "42000", "Percentage": "0.8", "Continent": "Europe", "Consumption pc": 64.47697793, "GDP pc": 49160.84, "Population": 896444, "Population (thousands)": 896.44}, {"Country": "France", "Muslim Population": "4704000", "Percentage": "7.5", "Continent": "Europe", "Consumption pc": 43.44321752, "GDP pc": 39037.12, "Population": 67379908, "Population (thousands)": 67379.91}, {"Country": "Gabon", "Muslim Population": "145000", "Percentage": "9.7", "Continent": "Africa", "Consumption pc": 4.447982862, "GDP pc": 6881.71, "Population": 2225728, "Population (thousands)": 2225.73}, {"Country": "Georgia", "Muslim Population": "442000", "Percentage": "10.5", "Continent": "Asia", "Consumption pc": 25.00862274, "GDP pc": 4255.74, "Population": 3722716, "Population (thousands)": 3722.72}, {"Country": "Germany", "Muslim Population": "4119000", "Percentage": "5.0", "Continent": "Europe", "Consumption pc": 24.29026988, "GDP pc": 46252.69, "Population": 83160871, "Population (thousands)": 83160.87}, {"Country": "Ghana", "Muslim Population": "3906000", "Percentage": "16.1", "Continent": "Africa", "Consumption pc": 0.273549868, "GDP pc": 2254.15, "Population": 31072945, "Population (thousands)": 31072.95}, {"Country": "Greece", "Muslim Population": "527000", "Percentage": "4.7", "Continent": "Europe", "Consumption pc": 30.35356294, "GDP pc": 17647.23, "Population": 10700556, "Population (thousands)": 10700.56}, {"Country": "Grenada", "Muslim Population": "< 1,000", "Percentage": "0.3", "Continent": "North America", "Consumption pc": 28.43964131, "GDP pc": 9273.2, "Population": 112519, "Population (thousands)": 112.52}, {"Country": "Guinea", "Muslim Population": "8693000", "Percentage": "84.2", "Continent": "Africa", "Consumption pc": 0.106603379, "GDP pc": 1078.95, "Population": 13132792, "Population (thousands)": 13132.79}, {"Country": "Guinea-Bissau", "Muslim Population": "705000", "Percentage": "42.8", "Continent": "Africa", "Consumption pc": 2.693092168, "GDP pc": 727.52, "Population": 1967998, "Population (thousands)": 1968.0}, {"Country": "Guyana", "Muslim Population": "55000", "Percentage": "7.2", "Continent": "South America", "Consumption pc": 0.0, "GDP pc": 6955.94, "Population": 786559, "Population (thousands)": 786.56}, {"Country": "Honduras", "Muslim Population": "11000", "Percentage": "0.1", "Continent": "North America", "Consumption pc": 0.111059418, "GDP pc": 2405.73, "Population": 9904608, "Population (thousands)": 9904.61}, {"Country": "Hong Kong", "Muslim Population": "91000", "Percentage": "1.3", "Continent": "Asia", "Consumption pc": 3.475471194, "GDP pc": 46100.98, "Population": 7481000, "Population (thousands)": 7481.0}, {"Country": "Hungary", "Muslim Population": "25000", "Percentage": "0.3", "Continent": "Europe", "Consumption pc": 24.0509145, "GDP pc": 16075.97, "Population": 9750149, "Population (thousands)": 9750.15}, {"Country": "Iceland", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "Europe", "Consumption pc": 12.82530569, "GDP pc": 59264.03, "Population": 366463, "Population (thousands)": 366.46}, {"Country": "India", "Muslim Population": "177286000", "Percentage": "14.6", "Continent": "Asia", "Consumption pc": 0.011594166, "GDP pc": 1933.1, "Population": 1380004385, "Population (thousands)": 1380004.39}, {"Country": "Indonesia", "Muslim Population": "204847000", "Percentage": "88.1", "Continent": "Asia", "Consumption pc": 0.0, "GDP pc": 3870.56, "Population": 273523621, "Population (thousands)": 273523.62}, {"Country": "Iraq", "Muslim Population": "31108000", "Percentage": "98.9", "Continent": "Asia", "Consumption pc": 0.007458511, "GDP pc": 4583.75, "Population": 40222503, "Population (thousands)": 40222.5}, {"Country": "Ireland", "Muslim Population": "43000", "Percentage": "0.9", "Continent": "Europe", "Consumption pc": 12.75655007, "GDP pc": 85422.54, "Population": 4985674, "Population (thousands)": 4985.67}, {"Country": "Israel", "Muslim Population": "1287000", "Percentage": "17.7", "Continent": "Asia", "Consumption pc": 0.661957005, "GDP pc": 44177.57, "Population": 9215100, "Population (thousands)": 9215.1}, {"Country": "Italy", "Muslim Population": "1583000", "Percentage": "2.6", "Continent": "Europe", "Consumption pc": 39.52933049, "GDP pc": 31834.97, "Population": 59449527, "Population (thousands)": 59449.53}, {"Country": "Japan", "Muslim Population": "185000", "Percentage": "0.1", "Continent": "Asia", "Consumption pc": 2.067146625, "GDP pc": 39918.17, "Population": 126261000, "Population (thousands)": 126261.0}, {"Country": "Jordan", "Muslim Population": "6397000", "Percentage": "98.8", "Continent": "Asia", "Consumption pc": 0.019601809, "GDP pc": 4282.77, "Population": 10203140, "Population (thousands)": 10203.14}, {"Country": "Kazakhstan", "Muslim Population": "8887000", "Percentage": "56.4", "Continent": "Asia", "Consumption pc": 1.40757465, "GDP pc": 9121.64, "Population": 18755666, "Population (thousands)": 18755.67}, {"Country": "Kenya", "Muslim Population": "2868000", "Percentage": "7.0", "Continent": "Africa", "Consumption pc": 0.081828038, "GDP pc": 1872.12, "Population": 53771300, "Population (thousands)": 53771.3}, {"Country": "Korea, Republic of", "Muslim Population": "75000", "Percentage": "0.2", "Continent": "Asia", "Consumption pc": 0.45142164, "GDP pc": 31597.5, "Population": 51836239, "Population (thousands)": 51836.24}, {"Country": "Kyrgyzstan", "Muslim Population": "4927000", "Percentage": "88.8", "Continent": "Asia", "Consumption pc": 0.379944984, "GDP pc": 1182.52, "Population": 6579900, "Population (thousands)": 6579.9}, {"Country": "Latvia", "Muslim Population": "2000", "Percentage": "0.1", "Continent": "Europe", "Consumption pc": 0.99976374, "GDP pc": 17703.95, "Population": 1900449, "Population (thousands)": 1900.45}, {"Country": "Lebanon", "Muslim Population": "2542000", "Percentage": "59.7", "Continent": "Asia", "Consumption pc": 0.864412883, "GDP pc": 3801.79, "Population": 6825442, "Population (thousands)": 6825.44}, {"Country": "Liberia", "Muslim Population": "523000", "Percentage": "12.8", "Continent": "Africa", "Consumption pc": 0.039543846, "GDP pc": 601.06, "Population": 5057677, "Population (thousands)": 5057.68}, {"Country": "Libya", "Muslim Population": "6325000", "Percentage": "96.6", "Continent": "Africa", "Consumption pc": 0.0, "GDP pc": 7614.33, "Population": 6871287, "Population (thousands)": 6871.29}, {"Country": "Lithuania", "Muslim Population": "3000", "Percentage": "0.1", "Continent": "Europe", "Consumption pc": 9.410047283, "GDP pc": 20232.3, "Population": 2794885, "Population (thousands)": 2794.89}, {"Country": "Luxembourg", "Muslim Population": "11000", "Percentage": "2.3", "Continent": "Europe", "Consumption pc": 42.98728306, "GDP pc": 116356.16, "Population": 630419, "Population (thousands)": 630.42}, {"Country": "Madagascar", "Muslim Population": "220000", "Percentage": "1.1", "Continent": "Africa", "Consumption pc": 0.325015125, "GDP pc": 477.61, "Population": 27691019, "Population (thousands)": 27691.02}, {"Country": "Malawi", "Muslim Population": "2011000", "Percentage": "12.8", "Continent": "Africa", "Consumption pc": 0.015682211, "GDP pc": 636.29, "Population": 19129955, "Population (thousands)": 19129.96}, {"Country": "Malaysia", "Muslim Population": "17139000", "Percentage": "61.4", "Continent": "Asia", "Consumption pc": 0.145214123, "GDP pc": 10412.35, "Population": 32365998, "Population (thousands)": 32366.0}, {"Country": "Maldives", "Muslim Population": "309000", "Percentage": "98.4", "Continent": "Asia", "Consumption pc": 2.219994006, "GDP pc": 6924.11, "Population": 540542, "Population (thousands)": 540.54}, {"Country": "Mali", "Muslim Population": "12316000", "Percentage": "92.4", "Continent": "Africa", "Consumption pc": 0.029628409, "GDP pc": 862.45, "Population": 20250834, "Population (thousands)": 20250.83}, {"Country": "Malta", "Muslim Population": "1000", "Percentage": "0.3", "Continent": "Europe", "Consumption pc": 12.61322798, "GDP pc": 28946.46, "Population": 515332, "Population (thousands)": 515.33}, {"Country": "Mauritius", "Muslim Population": "216000", "Percentage": "16.6", "Continent": "Africa", "Consumption pc": 1.422093005, "GDP pc": 8632.75, "Population": 1265740, "Population (thousands)": 1265.74}, {"Country": "Mexico", "Muslim Population": "111000", "Percentage": "0.1", "Continent": "North America", "Consumption pc": 0.476217242, "GDP pc": 8431.67, "Population": 128932753, "Population (thousands)": 128932.75}, {"Country": "Moldova", "Muslim Population": "15000", "Percentage": "0.4", "Continent": "Europe", "Consumption pc": 15.26429167, "GDP pc": 4525.76, "Population": 2620495, "Population (thousands)": 2620.5}, {"Country": "Mongolia", "Muslim Population": "120000", "Percentage": "4.4", "Continent": "Asia", "Consumption pc": 0.427051648, "GDP pc": 4060.95, "Population": 3278292, "Population (thousands)": 3278.29}, {"Country": "Montenegro", "Muslim Population": "116000", "Percentage": "18.5", "Continent": "Europe", "Consumption pc": 21.56747239, "GDP pc": 7694.63, "Population": 621306, "Population (thousands)": 621.31}, {"Country": "Morocco", "Muslim Population": "32381000", "Percentage": "99.9", "Continent": "Africa", "Consumption pc": 0.96178443, "GDP pc": 3058.69, "Population": 36910558, "Population (thousands)": 36910.56}, {"Country": "Mozambique", "Muslim Population": "5340000", "Percentage": "22.8", "Continent": "Africa", "Consumption pc": 0.073587202, "GDP pc": 448.84, "Population": 31255435, "Population (thousands)": 31255.44}, {"Country": "Myanmar", "Muslim Population": "1900000", "Percentage": "3.8", "Continent": "Asia", "Consumption pc": 0.02940647, "GDP pc": 1450.66, "Population": 54409794, "Population (thousands)": 54409.79}, {"Country": "Namibia", "Muslim Population": "9000", "Percentage": "0.4", "Continent": "Africa", "Consumption pc": 2.715556122, "GDP pc": 4157.02, "Population": 2540916, "Population (thousands)": 2540.92}, {"Country": "Nepal", "Muslim Population": "1253000", "Percentage": "4.2", "Continent": "Asia", "Consumption pc": 0.02059251, "GDP pc": 1147.47, "Population": 29136808, "Population (thousands)": 29136.81}, {"Country": "Netherlands", "Muslim Population": "914000", "Percentage": "5.5", "Continent": "Europe", "Consumption pc": 20.06708139, "GDP pc": 52396.03, "Population": 17441500, "Population (thousands)": 17441.5}, {"Country": "New Caledonia", "Muslim Population": "7000", "Percentage": "2.8", "Continent": "Oceania", "Consumption pc": 23.53287248, "GDP pc": 34694.55, "Population": 271960, "Population (thousands)": 271.96}, {"Country": "New Zealand", "Muslim Population": "41000", "Percentage": "0.9", "Continent": "Oceani