<a href="https://colab.research.google.com/github/jtinklerdav/jtinklerdav.github.io/blob/main/Project/regression_Islam_consumption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests

Now I am creating a dataframe that is reading the html code of the website below. This code reads the html and selects the tables from the site. By using inspect element I was able to determine that the table could be scraped in Colab. The Table shows the Muslim population in every country in a study conducted by the Pew Forum Research Centre

In [2]:
df = pd.read_html('https://web.archive.org/web/20110202124356/http://features.pewforum.org/muslim-population/')
df

[      0     1     2
 0   Jan   FEB   Apr
 1   NaN    02   NaN
 2  2010  2011  2012,
                Country Estimated 1990 Muslim Population  \
 0          Afghanistan                         12551000
 1              Albania                          2302000
 2              Algeria                         24860000
 3       American Samoa                          < 1,000
 4              Andorra                          < 1,000
 ..                 ...                              ...
 227  Wallis and Futuna                          < 1,000
 228     Western Sahara                           221000
 229              Yemen                         12191000
 230             Zambia                            33000
 231           Zimbabwe                            94000

     Percentage of 1990 Population that is Muslim  \
 0                                           99.8
 1                                           70.0
 2                                           98.3
 3                                          < 0.1
 4                                            0.5
 ..                                           ...
 227                                        < 0.1
 228                                         99.9
 229                                         99.0
 230                                          0.4
 231                                          0.9

     Estimated 2010 Muslim Population  \
 0                           29047000
 1                            2601000
 2                           34780000
 3                            < 1,000
 4                               1000
 ..                               ...
 227                          < 1,000
 228                           528000
 229                         24023000
 230                            59000
 231                           109000

     Percentage of 2010 Population that is Muslim  \
 0                                           99.8
 1                                           82.1
 2                                           98.2
 3                                          < 0.1
 4                                            1.1
 ..                                           ...
 227                                        < 0.1
 228                                         99.6
 229                                         99.0
 230                                          0.4
 231                                          0.9

     Projected 2030 Muslim Population*  \
 0                            50527000
 1                             2841000
 2                            43915000
 3                             < 1,000
 4                                1000
 ..                                ...
 227                           < 1,000
 228                            816000
 229                          38973000
 230                             94000
 231                            155000

     Projected Percentage of 2030 Population that is Muslim*
 0                                                 99.8
 1                                                 83.2
 2                                                 98.2
 3                                                < 0.1
 4                                                  1.1
 ..                                                 ...
 227                                              < 0.1
 228                                               99.6
 229                                               99.0
 230                                                0.4
 231                                                0.9

 [232 rows x 7 columns]]

Having created a dataframe with the tables from the site, I am checking how many tables are in the array scraped and which one has the data desired. From using the len() function I know that there are 2 tables in the array and from looking at each one I know that the second table in the array contains the desired information

In [3]:
len(df)

2

In [9]:
df2 = df[1]
df2

,Country,Estimated 1990 Muslim Population,Percentage of 1990 Population that is Muslim,Estimated 2010 Muslim Population,Percentage of 2010 Population that is Muslim,Projected 2030 Muslim Population*,Projected Percentage of 2030 Population that is Muslim*
0,Afghanistan,12551000,99.8,29047000,99.8,50527000,99.8
1,Albania,2302000,70.0,2601000,82.1,2841000,83.2
2,Algeria,24860000,98.3,34780000,98.2,43915000,98.2
3,American Samoa,"< 1,000",< 0.1,"< 1,000",< 0.1,"< 1,000",< 0.1
4,Andorra,"< 1,000",0.5,1000,1.1,1000,1.1
...,...,...,...,...,...,...,...
227,Wallis and Futuna,"< 1,000",< 0.1,"< 1,000",< 0.1,"< 1,000",< 0.1
228,Western Sahara,221000,99.9,528000,99.6,816000,99.6
229,Yemen,12191000,99.0,24023000,99.0,38973000,99.0
230,Zambia,33000,0.4,59000,0.4,94000,0.4
231,Zimbabwe,94000,0.9,109000,0.9,155000,0.9

Now that I have scraped the table succeffully into Colab I am dropping the columns that are unnecessary for the regression I am going to undertake. These are the Projections for 2030 and the 1990 values. I am also renaming the columns to simplify my code

In [10]:
df3 = df2.drop(['Estimated 1990 Muslim Population','Percentage of 1990 Population that is Muslim','Projected 2030 Muslim Population*','Projected Percentage of 2030 Population that is Muslim*'],axis=1)
df3

,Country,Estimated 2010 Muslim Population,Percentage of 2010 Population that is Muslim
0,Afghanistan,29047000,99.8
1,Albania,2601000,82.1
2,Algeria,34780000,98.2
3,American Samoa,"< 1,000",< 0.1
4,Andorra,1000,1.1
...,...,...,...
227,Wallis and Futuna,"< 1,000",< 0.1
228,Western Sahara,528000,99.6
229,Yemen,24023000,99.0
230,Zambia,59000,0.4
231,Zimbabwe,109000,0.9

In [79]:
df4 = df3.rename(columns={'Estimated 2010 Muslim Population':'Muslim Population','Percentage of 2010 Population that is Muslim':'Percentage'})

Having renamed the columns I needed to rename a number of the Country names so that they would maytch up with the other dataset when merging the two. Therefore I manually sorted through the data and renamed the required countries so as to not affect the dataset

In [89]:
df4['Country'] = df4['Country'].replace({'Swaziland': 'Eswatini','Congo':'The Democratic Republic of Congo','Cape Verde':'Cabo Verde','Guinea Bissau':'Guinea-Bissau',"Ivory Coast":"Cote d'Ivoire", 'Laos':"Lao People's Democratic Republic",'Burma (Myanmar)': 'Myanmar', 'South Korea':'Korea, Republic of', 'Faeroe Islands':'Faroe Islands','Bosnia-Herzegovina':'Bosnia and Herzegovina','Republic of Macedonia': 'North Macedonia', 'Slovakia':'Slovak Republic','Czech Republic':'Czechia','Russia':"Russian Federation",'St. Kitts and Nevis': 'Saint Kitts and Nevis','St. Vincent and the Grenadines':'Saint Vincent and the Grenadines','St. Lucia':'Saint Lucia','Macau':'Macao'})
df5=df4

               Country Muslim Population Percentage
0          Afghanistan          29047000       99.8
1              Albania           2601000       82.1
2              Algeria          34780000       98.2
3       American Samoa           < 1,000      < 0.1
4              Andorra              1000        1.1
..                 ...               ...        ...
227  Wallis and Futuna           < 1,000      < 0.1
228     Western Sahara            528000       99.6
229              Yemen          24023000       99.0
230             Zambia             59000        0.4
231           Zimbabwe            109000        0.9

[232 rows x 3 columns]

Now that I have my cleaned data for the first source (Muslim %), I am importing a csv of Wine Consumption per capita (calculated in Excel).

In [93]:
df2_1 = pd.read_csv('regression_data.csv')
df2_1

,Continent,Country Name,GDP pc,Consumption,Population,Consumption (litres),Consumption pc,Population (thousands)
0,Asia,Afghanistan,516.75,1,38928341,100000,0.00257,38928.34
1,Africa,Libya,7614.33,1,6871287,100000,0.01455,6871.29
2,Africa,Chad,652.35,2,16425859,200000,0.01218,16425.86
3,Africa,Djibouti,3219.70,2,988002,200000,0.20243,988.00
4,Africa,Malawi,636.29,2,19129955,200000,0.01045,19129.96
...,...,...,...,...,...,...,...,...
162,Africa,Nigeria,2097.09,279,206139587,27900000,0.13535,206139.59
163,Oceania,New Zealand,41596.51,950,5090200,95000000,18.66331,5090.20
164,South America,Chile,13220.57,1826,19116209,182600000,9.55210,19116.21
165,Africa,South Africa,5655.87,3138,59308690,313800000,5.29096,59308.69
166,Oceania,Australia,51680.32,5950,25693267,595000000,23.15782,25693.27

In [94]:
df2_2 = df2_1.drop(['Consumption'],axis=1)
df2_2

,Continent,Country Name,GDP pc,Population,Consumption (litres),Consumption pc,Population (thousands)
0,Asia,Afghanistan,516.75,38928341,100000,0.00257,38928.34
1,Africa,Libya,7614.33,6871287,100000,0.01455,6871.29
2,Africa,Chad,652.35,16425859,200000,0.01218,16425.86
3,Africa,Djibouti,3219.70,988002,200000,0.20243,988.00
4,Africa,Malawi,636.29,19129955,200000,0.01045,19129.96
...,...,...,...,...,...,...,...
162,Africa,Nigeria,2097.09,206139587,27900000,0.13535,206139.59
163,Oceania,New Zealand,41596.51,5090200,95000000,18.66331,5090.20
164,South America,Chile,13220.57,19116209,182600000,9.55210,19116.21
165,Africa,South Africa,5655.87,59308690,313800000,5.29096,59308.69
166,Oceania,Australia,51680.32,25693267,595000000,23.15782,25693.27

In [95]:
df2_3 = df2_2.rename(columns={'Country Name': 'Country'})

I had to rename the 'Country Name' column since the two columns need to match up when merging datasets. Below I have merged the two datasets. In the code I have merged based on Country name (hence why editing the names was so vital earlier) and i have merged it on the 'right' dataset. This is the df2_3 dataset since it has fewer values so less sorting is required after merging

In [96]:
merge_df = df5.merge(df2_3, on=['Country'], how='right')
merge_df

,Country,Muslim Population,Percentage,Continent,GDP pc,Population,Consumption (litres),Consumption pc,Population (thousands)
0,Afghanistan,29047000,99.8,Asia,516.75,38928341,100000,0.00257,38928.34
1,Libya,6325000,96.6,Africa,7614.33,6871287,100000,0.01455,6871.29
2,Chad,6404000,55.7,Africa,652.35,16425859,200000,0.01218,16425.86
3,Djibouti,853000,97.0,Africa,3219.70,988002,200000,0.20243,988.00
4,Malawi,2011000,12.8,Africa,636.29,19129955,200000,0.01045,19129.96
...,...,...,...,...,...,...,...,...,...
162,Nigeria,75728000,47.9,Africa,2097.09,206139587,27900000,0.13535,206139.59
163,New Zealand,41000,0.9,Oceania,41596.51,5090200,95000000,18.66331,5090.20
164,Chile,4000,< 0.1,South America,13220.57,19116209,182600000,9.55210,19116.21
165,South Africa,737000,1.5,Africa,5655.87,59308690,313800000,5.29096,59308.69
166,Australia,399000,1.9,Oceania,51680.32,25693267,595000000,23.15782,25693.27

Having done this I recognised that some of the data in the table will affect my regression. Since I am regressing percentage I need to remove all the observations that are labelled "<0.1", they are not numeric values and are nearing 0 so I have removed them at the extremety of observations

I used the drop() function to remove all the rows with that as their value for Percentage

In [97]:
merge_df2 = merge_df.drop(merge_df[merge_df['Percentage']=='< 0.1'].index)

,Country,Muslim Population,Percentage,Continent,GDP pc,Population,Consumption (litres),Consumption pc,Population (thousands)
0,Afghanistan,29047000,99.8,Asia,516.75,38928341,100000,0.00257,38928.34
1,Libya,6325000,96.6,Africa,7614.33,6871287,100000,0.01455,6871.29
2,Chad,6404000,55.7,Africa,652.35,16425859,200000,0.01218,16425.86
3,Djibouti,853000,97.0,Africa,3219.70,988002,200000,0.20243,988.00
4,Malawi,2011000,12.8,Africa,636.29,19129955,200000,0.01045,19129.96
...,...,...,...,...,...,...,...,...,...
161,Burkina Faso,9600000,58.9,Africa,857.93,20903278,11400000,0.54537,20903.28
162,Nigeria,75728000,47.9,Africa,2097.09,206139587,27900000,0.13535,206139.59
163,New Zealand,41000,0.9,Oceania,41596.51,5090200,95000000,18.66331,5090.20
165,South Africa,737000,1.5,Africa,5655.87,59308690,313800000,5.29096,59308.69
166,Australia,399000,1.9,Oceania,51680.32,25693267,595000000,23.15782,25693.27

In [99]:
exported_values = list(merge_df2.T.to_dict().values())

In [100]:
import json

In [101]:
open('regression.json','w').write(json.dumps(exported_values))

33695

In [102]:
json.dumps(exported_values)

'[{"Country": "Afghanistan", "Muslim Population": "29047000", "Percentage": "99.8", "Continent": "Asia", "GDP pc": 516.75, "Population": 38928341, "Consumption (litres)": 100000, "Consumption pc": 0.00257, "Population (thousands)": 38928.34}, {"Country": "Libya", "Muslim Population": "6325000", "Percentage": "96.6", "Continent": "Africa", "GDP pc": 7614.33, "Population": 6871287, "Consumption (litres)": 100000, "Consumption pc": 0.01455, "Population (thousands)": 6871.29}, {"Country": "Chad", "Muslim Population": "6404000", "Percentage": "55.7", "Continent": "Africa", "GDP pc": 652.35, "Population": 16425859, "Consumption (litres)": 200000, "Consumption pc": 0.01218, "Population (thousands)": 16425.86}, {"Country": "Djibouti", "Muslim Population": "853000", "Percentage": "97.0", "Continent": "Africa", "GDP pc": 3219.7, "Population": 988002, "Consumption (litres)": 200000, "Consumption pc": 0.20243, "Population (thousands)": 988.0}, {"Country": "Malawi", "Muslim Population": "2011000", "Percentage": "12.8", "Continent": "Africa", "GDP pc": 636.29, "Population": 19129955, "Consumption (litres)": 200000, "Consumption pc": 0.01045, "Population (thousands)": 19129.96}, {"Country": "Comoros", "Muslim Population": "679000", "Percentage": "98.3", "Continent": "Africa", "GDP pc": 1407.41, "Population": 869595, "Consumption (litres)": 300000, "Consumption pc": 0.34499, "Population (thousands)": 869.6}, {"Country": "Sierra Leone", "Muslim Population": "4171000", "Percentage": "71.5", "Continent": "Africa", "GDP pc": 509.38, "Population": 7976985, "Consumption (litres)": 300000, "Consumption pc": 0.03761, "Population (thousands)": 7976.99}, {"Country": "Sudan", "Muslim Population": "30855000", "Percentage": "71.4", "Continent": "Africa", "GDP pc": 615.46, "Population": 43849269, "Consumption (litres)": 300000, "Consumption pc": 0.00684, "Population (thousands)": 43849.27}, {"Country": "Burundi", "Muslim Population": "184000", "Percentage": "2.2", "Continent": "Africa", "GDP pc": 233.84, "Population": 11890781, "Consumption (litres)": 400000, "Consumption pc": 0.03364, "Population (thousands)": 11890.78}, {"Country": "Central African Republic", "Muslim Population": "403000", "Percentage": "8.9", "Continent": "Africa", "GDP pc": 481.75, "Population": 4829764, "Consumption (litres)": 400000, "Consumption pc": 0.08282, "Population (thousands)": 4829.76}, {"Country": "Eswatini", "Muslim Population": "2000", "Percentage": "0.2", "Continent": "Africa", "GDP pc": 3434.72, "Population": 1329479, "Consumption (litres)": 400000, "Consumption pc": 0.30087, "Population (thousands)": 1329.48}, {"Country": "Ethiopia", "Muslim Population": "28721000", "Percentage": "33.8", "Continent": "Africa", "GDP pc": 936.45, "Population": 1160164, "Consumption (litres)": 800000, "Consumption pc": 0.68956, "Population (thousands)": 1160.16}, {"Country": "Liberia", "Muslim Population": "523000", "Percentage": "12.8", "Continent": "Africa", "GDP pc": 601.06, "Population": 5057677, "Consumption (litres)": 800000, "Consumption pc": 0.15818, "Population (thousands)": 5057.68}, {"Country": "Guinea", "Muslim Population": "8693000", "Percentage": "84.2", "Continent": "Africa", "GDP pc": 1078.95, "Population": 13132792, "Consumption (litres)": 900000, "Consumption pc": 0.06853, "Population (thousands)": 13132.79}, {"Country": "Uganda", "Muslim Population": "4060000", "Percentage": "12.0", "Continent": "Africa", "GDP pc": 822.03, "Population": 45741000, "Consumption (litres)": 1200000, "Consumption pc": 0.02623, "Population (thousands)": 45741.0}, {"Country": "Mauritius", "Muslim Population": "216000", "Percentage": "16.6", "Continent": "Africa", "GDP pc": 8632.75, "Population": 1265740, "Consumption (litres)": 1600000, "Consumption pc": 1.26408, "Population (thousands)": 1265.74}, {"Country": "Rwanda", "Muslim Population": "188000", "Percentage": "1.8", "Continent": "Africa", "GDP pc": 786.3, "Population": 12952209, "Consumption (litres)": 1700000, "Consumption pc": 0.13125, "Population (thousands)": 12952.21}, {"Country": "Mali", "Muslim Population": "12316000", "Percentage": "92.4", "Continent": "Africa", "GDP pc": 862.45, "Population": 20250834, "Consumption (litres)": 1900000, "Consumption pc": 0.09382, "Population (thousands)": 20250.83}, {"Country": "Republic of Congo", "Muslim Population": "60000", "Percentage": "1.6", "Continent": "Africa", "GDP pc": 1899.78, "Population": 5518092, "Consumption (litres)": 2200000, "Consumption pc": 0.39869, "Population (thousands)": 5518.09}, {"Country": "Zimbabwe", "Muslim Population": "109000", "Percentage": "0.9", "Continent": "Africa", "GDP pc": 1214.51, "Population": 14862927, "Consumption (litres)": 2200000, "Consumption pc": 0.14802, "Population (thousands)": 14862.93}, {"Country": "Benin", "Muslim Population": "2259000", "Percentage": "24.5", "Continent": "Africa", "GDP pc": 1291.04, "Population": 12123198, "Consumption (litres)": 2300000, "Consumption pc": 0.18972, "Population (thousands)": 12123.2}, {"Country": "Mozambique", "Muslim Population": "5340000", "Percentage": "22.8", "Continent": "Africa", "GDP pc": 448.84, "Population": 31255435, "Consumption (litres)": 2400000, "Consumption pc": 0.07679, "Population (thousands)": 31255.44}, {"Country": "Zambia", "Muslim Population": "59000", "Percentage": "0.4", "Continent": "Africa", "GDP pc": 985.13, "Population": 18383956, "Consumption (litres)": 2700000, "Consumption pc": 0.14687, "Population (thousands)": 18383.96}, {"Country": "Tanzania", "Muslim Population": "13450000", "Percentage": "29.9", "Continent": "Africa", "GDP pc": 1076.47, "Population": 59734213, "Consumption (litres)": 2900000, "Consumption pc": 0.04855, "Population (thousands)": 59734.21}, {"Country": "The Democratic Republic of Congo", "Muslim Population": "969000", "Percentage": "1.4", "Continent": "Africa", "GDP pc": 543.95, "Population": 89561404, "Consumption (litres)": 3300000, "Consumption pc": 0.03685, "Population (thousands)": 89561.4}, {"Country": "Botswana", "Muslim Population": "8000", "Percentage": "0.4", "Continent": "Africa", "GDP pc": 6348.83, "Population": 2351625, "Consumption (litres)": 4600000, "Consumption pc": 1.95609, "Population (thousands)": 2351.63}, {"Country": "Gabon", "Muslim Population": "145000", "Percentage": "9.7", "Continent": "Africa", "GDP pc": 6881.71, "Population": 2225728, "Consumption (litres)": 5400000, "Consumption pc": 2.42617, "Population (thousands)": 2225.73}, {"Country": "Senegal", "Muslim Population": "12333000", "Percentage": "95.9", "Continent": "Africa", "GDP pc": 1462.81, "Population": 16743930, "Consumption (litres)": 5400000, "Consumption pc": 0.3225, "Population (thousands)": 16743.93}, {"Country": "Egypt", "Muslim Population": "80024000", "Percentage": "94.7", "Continent": "Africa", "GDP pc": 3569.21, "Population": 102334403, "Consumption (litres)": 5700000, "Consumption pc": 0.0557, "Population (thousands)": 102334.4}, {"Country": "Cabo Verde", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "Africa", "GDP pc": 3064.27, "Population": 555988, "Consumption (litres)": 6800000, "Consumption pc": 12.23048, "Population (thousands)": 555.99}, {"Country": "Ghana", "Muslim Population": "3906000", "Percentage": "16.1", "Continent": "Africa", "GDP pc": 2254.15, "Population": 31072945, "Consumption (litres)": 6800000, "Consumption pc": 0.21884, "Population (thousands)": 31072.95}, {"Country": "Kenya", "Muslim Population": "2868000", "Percentage": "7.0", "Continent": "Africa", "GDP pc": 1872.12, "Population": 53771300, "Consumption (litres)": 7100000, "Consumption pc": 0.13204, "Population (thousands)": 53771.3}, {"Country": "Madagascar", "Muslim Population": "220000", "Percentage": "1.1", "Continent": "Africa", "GDP pc": 477.61, "Population": 27691019, "Consumption (litres)": 8800000, "Consumption pc": 0.31779, "Population (thousands)": 27691.02}, {"Country": "Guinea-Bissau", "Muslim Population": "705000", "Percentage": "42.8", "Continent": "Africa", "GDP pc": 727.52, "Population": 1967998, "Consumption (litres)": 10000000, "Consumption pc": 5.08131, "Population (thousands)": 1968.0}, {"Country": "Cameroon", "Muslim Population": "3598000", "Percentage": "18.0", "Continent": "Africa", "GDP pc": 1537.13, "Population": 26545864, "Consumption (litres)": 13600000, "Consumption pc": 0.51232, "Population (thousands)": 26545.86}, {"Country": "Angola", "Muslim Population": "195000", "Percentage": "1.0", "Continent": "Africa", "GDP pc": 1631.43, "Population": 32866268, "Consumption (litres)": 31700000, "Consumption pc": 0.96451, "Population (thousands)": 32866.27}, {"Country": "Tunisia", "Muslim Population": "10349000", "Percentage": "99.8", "Continent": "Africa", "GDP pc": 3597.22, "Population": 11818618, "Consumption (litres)": 31800000, "Consumption pc": 2.69067, "Population (thousands)": 11818.62}, {"Country": "Namibia", "Muslim Population": "9000", "Percentage": "0.4", "Continent": "Africa", "GDP pc": 4157.02, "Population": 2540916, "Consumption (litres)": 38100000, "Consumption pc": 14.99459, "Population (thousands)": 2540.92}, {"Country": "Cote d\'Ivoire", "Muslim Population": "7960000", "Percentage": "36.9", "Continent": "Africa", "GDP pc": 2325.72, "Population": 26378275, "Consumption (litres)": 40400000, "Consumption pc": 1.53156, "Population (thousands)": 26378.28}, {"Country": "Algeria", "Muslim Population": "34780000", "Percentage": "98.2", "Continent": "Africa", "GDP pc": 3306.86, "Population": 43851043, "Consumption (litres)": 45500000, "Consumption pc": 1.0376, "Population (thousands)": 43851.04}, {"Country": "Morocco", "Muslim Population": "32381000", "Percentage": "99.9", "Continent": "Africa", "GDP pc": 3058.69, "Population": 36910558, "Consumption (litres)": 59600000, "Consumption pc": 1.61471, "Population (thousands)": 36910.56}, {"Country": "Bangladesh", "Muslim Population": "148607000", "Percentage": "90.4", "Continent": "Asia", "GDP pc": 2270.35, "Population": 164689383, "Consumption (litres)": 100000, "Consumption pc": 0.00061, "Population (thousands)": 164689.38}, {"Country": "Jordan", "Muslim Population": "6397000", "Percentage": "98.8", "Continent": "Asia", "GDP pc": 4282.77, "Population": 10203140, "Consumption (litres)": 300000, "Consumption pc": 0.0294, "Population (thousands)": 10203.14}, {"Country": "Tajikistan", "Muslim Population": "7006000", "Percentage": "99.0", "Continent": "Asia", "GDP pc": 852.83, "Population": 9537642, "Consumption (litres)": 400000, "Consumption pc": 0.04194, "Population (thousands)": 9537.64}, {"Country": "Nepal", "Muslim Population": "1253000", "Percentage": "4.2", "Continent": "Asia", "GDP pc": 1147.47, "Population": 29136808, "Consumption (litres)": 700000, "Consumption pc": 0.02402, "Population (thousands)": 29136.81}, {"Country": "Iraq", "Muslim Population": "31108000", "Percentage": "98.9", "Continent": "Asia", "GDP pc": 4583.75, "Population": 40222503, "Consumption (litres)": 1000000, "Consumption pc": 0.02486, "Population (thousands)": 40222.5}, {"Country": "Thailand", "Muslim Population": "3952000", "Percentage": "5.8", "Continent": "Asia", "GDP pc": 7158.77, "Population": 69799978, "Consumption (litres)": 1000000, "Consumption pc": 0.01433, "Population (thousands)": 69799.98}, {"Country": "Sri Lanka", "Muslim Population": "1725000", "Percentage": "8.5", "Continent": "Asia", "GDP pc": 3694.04, "Population": 21919000, "Consumption (litres)": 1100000, "Consumption pc": 0.05018, "Population (thousands)": 21919.0}, {"Country": "Cambodia", "Muslim Population": "240000", "Percentage": "1.6", "Continent": "Asia", "GDP pc": 1547.51, "Population": 16718971, "Consumption (litres)": 1200000, "Consumption pc": 0.07177, "Population (thousands)": 16718.97}, {"Country": "Bahrain", "Muslim Population": "655000", "Percentage": "81.2", "Continent": "Asia", "GDP pc": 20406.5, "Population": 1701583, "Consumption (litres)": 1500000, "Consumption pc": 0.88153, "Population (thousands)": 1701.58}, {"Country": "Seychelles", "Muslim Population": "< 1,000", "Percentage": "1.1", "Continent": "Asia", "GDP pc": 12193.89, "Population": 98462, "Consumption (litres)": 1700000, "Consumption pc": 17.26554, "Population (thousands)": 98.46}, {"Country": "Mongolia", "Muslim Population": "120000", "Percentage": "4.4", "Continent": "Asia", "GDP pc": 4060.95, "Population": 3278292, "Consumption (litres)": 1800000, "Consumption pc": 0.54907, "Population (thousands)": 3278.29}, {"Country": "Maldives", "Muslim Population": "309000", "Percentage": "98.4", "Continent": "Asia", "GDP pc": 6924.11, "Population": 540542, "Consumption (litres)": 2200000, "Consumption pc": 4.06999, "Population (thousands)": 540.54}, {"Country": "Indonesia", "Muslim Population": "204847000", "Percentage": "88.1", "Continent": "Asia", "GDP pc": 3870.56, "Population": 273523621, "Consumption (litres)": 2500000, "Consumption pc": 0.00914, "Population (thousands)": 273523.62}, {"Country": "Kyrgyzstan", "Muslim Population": "4927000", "Percentage": "88.8", "Continent": "Asia", "GDP pc": 1182.52, "Population": 6579900, "Consumption (litres)": 3400000, "Consumption pc": 0.51673, "Population (thousands)": 6579.9}, {"Country": "Israel", "Muslim Population": "1287000", "Percentage": "17.7", "Continent": "Asia", "GDP pc": 44177.57, "Population": 9215100, "Consumption (litres)": 4300000, "Consumption pc": 0.46663, "Population (thousands)": 9215.1}, {"Country": "Myanmar", "Muslim Population": "1900000", "Percentage": "3.8", "Continent": "Asia", "GDP pc": 1450.66, "Population": 54409794, "Consumption (litres)": 5700000, "Consumption pc": 0.10476, "Population (thousands)": 54409.79}, {"Country": "Malaysia", "Muslim Population": "17139000", "Percentage": "61.4", "Continent": "Asia", "GDP pc": 10412.35, "Population": 32365998, "Consumption (litres)": 6200000, "Consumption pc": 0.19156, "Population (thousands)": 32366.0}, {"Country": "Lebanon", "Muslim Population": "2542000", "Percentage": "59.7", "Continent": "Asia", "GDP pc": 3801.79, "Population": 6825442, "Consumption (litres)": 8800000, "Consumption pc": 1.28929, "Population (thousands)": 6825.44}, {"Country": "Azerbaijan", "Muslim Population": "8795000", "Percentage": "98.4", "Continent": "Asia", "GDP pc": 4229.91, "Population": 10093121, "Consumption (litres)": 10800000, "Consumption pc": 1.07004, "Population (thousands)": 10093.12}, {"Country": "Vietnam", "Muslim Population": "160000", "Percentage": "0.2", "Continent": "Asia", "GDP pc": 3526.27, "Population": 97338583, "Consumption (litres)": 12000000, "Consumption pc": 0.12328, "Population (thousands)": 97338.58}, {"Country": "Singapore", "Muslim Population": "721000", "Percentage": "14.9", "Continent": "Asia", "GDP pc": 60729.45, "Population": 5685807, "Consumption (litres)": 15700000, "Consumption pc": 2.76126, "Population (thousands)": 5685.81}, {"Country": "Uzbekistan", "Muslim Population": "26833000", "Percentage": "96.5", "Continent": "Asia", "GDP pc": 1749.66, "Population": 34232050, "Consumption (litres)": 15700000, "Consumption pc": 0.45863, "Population (thousands)": 34232.05}, {"Country": "India", "Muslim Population": "177286000", "Percentage": "14.6", "Continent": "Asia", "GDP pc": 1933.1, "Population": 1380004385, "Consumption (litres)": 21200000, "Consumption pc": 0.01536, "Population (thousands)": 1380004.39}, {"Country": "Philippines", "Muslim Population": "4737000", "Percentage": "5.1", "Continent": "Asia", "GDP pc": 3301.22, "Population": 109581085, "Consumption (litres)": 22800000, "Consumption pc": 0.20807, "Population (thousands)": 109581.09}, {"Country": "Hong Kong", "Muslim Population": "91000", "Percentage": "1.3", "Continent": "Asia", "GDP pc": 46100.98, "Population": 7481000, "Consumption (litres)": 30700000, "Consumption pc": 4.10373, "Population (thousands)": 7481.0}, {"Country": "Korea, Republic of", "Muslim Population": "75000", "Percentage": "0.2", "Continent": "Asia", "GDP pc": 31597.5, "Population": 51836239, "Consumption (litres)": 49100000, "Consumption pc": 0.94721, "Population (thousands)": 51836.24}, {"Country": "Kazakhstan", "Muslim Population": "8887000", "Percentage": "56.4", "Continent": "Asia", "GDP pc": 9121.64, "Population": 18755666, "Consumption (litres)": 54000000, "Consumption pc": 2.87913, "Population (thousands)": 18755.67}, {"Country": "Georgia", "Muslim Population": "442000", "Percentage": "10.5", "Continent": "Asia", "GDP pc": 4255.74, "Population": 3722716, "Consumption (litres)": 109000000, "Consumption pc": 29.2797, "Population (thousands)": 3722.72}, {"Country": "Japan", "Muslim Population": "185000", "Percentage": "0.1", "Continent": "Asia", "GDP pc": 39918.17, "Population": 126261000, "Consumption (litres)": 348200000, "Consumption pc": 2.75778, "Population (thousands)": 126261.0}, {"Country": "China", "Muslim Population": "23308000", "Percentage": "1.8", "Continent": "Asia", "GDP pc": 10408.67, "Population": 1411100000, "Consumption (litres)": 1239600000, "Consumption pc": 0.87846, "Population (thousands)": 1411100.0}, {"Country": "Iceland", "Muslim Population": "< 1,000", "Percentage": "0.1", "Continent": "Europe", "GDP pc": 59264.03, "Population": 366463, "Consumption (litres)": 5000000, "Consumption pc": 13.64394, "Population (thousands)": 366.46}, {"Country": "Malta", "Muslim Population": "1000", "Percentage": "0.3", "Continent": "Europe", "GDP pc": 28946.46, "Population": 515332, "Consumption (litres)": 7100000, "Consumption pc": 13.77753, "Population (thousands)": 515.33}, {"Country": "Latvia", "Muslim Population": "2000", "Percentage": "0.1", "Continent": "Europe", "GDP pc": 17703.95, "Population": 1900449, "Consumption (litres)": 8300000, "Consumption pc": 4.36739, "Population (thousands)": 1900.45}, {"Country": "Montenegro", "Muslim Population": "116000", "Percentage": "18.5", "Continent": "Europe", "GDP pc": 7694.63, "Population": 621306, "Consumption (litres)": 10900000, "Consumption pc": 17.54369, "Population (thousands)": 621.31}, {"Country": "Bosnia and Herzegovina", "Muslim Population": "1564000", "Percentage": "41.6", "Continent": "Europe", "GDP pc": 6082.37, "Population": 3280815, "Consumption (litres)": 11100000, "Consumption pc": 3.38331, "Population (thousands)": 3280.82}, {"Country": "Cyprus", "Muslim Population": "200000", "Percentage": "22.7", "Continent": "Europe", "GDP pc": 27681.57, "Population": 1207361, "Consumption (litres)": 16400000, "Consumption pc": 13.58334, "Population (thousands)": 1207.36}, {"Country": "Albania", "Muslim Population": "2601000", "Percentage": "82.1", "Continent": "Europe", "GDP pc": 5332.16, "Population": 2837849, "Consumption (litres)": 20500000, "Consumption pc": 7.22378, "Population (thousands)": 2837.85}, {"Country": "Finland", "Muslim Population": "42000", "Percentage": "0.8", "Continent": "Europe", "GDP pc": 49160.84, "Population": 896444, "Consumption (litres)": 23200000, "Consumption pc": 25.88003, "Population (thousands)": 896.44}, {"Country": "Luxembourg", "Muslim Population": "11000", "Percentage": "2.3", "Continent": "Europe", "GDP pc": 116356.16, "Population": 630419, "Consumption (litres)": 25700000, "Consumption pc": 40.76654, "Population (thousands)": 630.42}, {"Country": "North Macedonia", "Muslim Population": "713000", "Percentage": "34.9", "Continent": "Europe", "GDP pc": 5846.47, "Population": 2072531, "Consumption (litres)": 26500000, "Consumption pc": 12.7863, "Population (thousands)": 2072.53}, {"Country": "Estonia", "Muslim Population": "2000", "Percentage": "0.1", "Continent": "Europe", "GDP pc": 23054.36, "Population": 1402985, "Consumption (litres)": 27500000, "Consumption pc": 19.60106, "Population (thousands)": 1402.99}, {"Country": "Moldova", "Muslim Population": "15000", "Percentage": "0.4", "Continent": "Europe", "GDP pc": 4525.76, "Population": 2620495, "Consumption (litres)": 32900000, "Consumption pc": 12.55488, "Population (thousands)": 2620.5}, {"Country": "Lithuania", "Muslim Population": "3000", "Percentage": "0.1", "Continent": "Europe", "GDP pc": 20232.3, "Population": 2794885, "Consumption (litres)": 3